Repository dohyeon5626/huraypositive-extension, pull requests merged in 2024-01, with the labels that each got.

#24 [ADD] 회의실 실시간 상태 변경 기능 추가
  src/views/meeting-room.ts
Labels: feature

#26 [FIX] 간혹 클릭이 되어도 일정이 안 보여지는 문제 해결
  src/views/meeting-room.ts
Labels: bug

#28 [ADD] 편의성을 위한 명령어 추가
  .gitignore
  package.json
Labels: base

#33 [UPDATE] 불필요한 import 제거 및 리팩토링
  src/api/google.ts
  src/background/router.ts
  src/views/meeting-room.ts
  src/views/spread-search.ts
Labels: feature

#36 [ FIX] 스프레드시트 검색창 enter시 오류
  src/views/spread-search.ts
Labels: bug

#35 [UPDATE] 정각이나 30분의 경우에는 다시 캘린더 정보를 가지고 오도록 설정
  src/util/date.ts
  src/views/meeting-room.ts
Labels: feature

#34 [ADD] 오류가 날때 파악을 하기 위한 로그 설정
  public/popup.css
  src/api/chrome.ts
  src/background/base.ts
  src/background/router.ts
  src/content/calendar.ts
  src/content/spread.ts
  src/content/swagger.ts
  src/etc/func-base.ts
  src/etc/test-mode.ts
  src/popup/popup.ts
  src/views/function.ts
  src/views/meeting-room.ts
  src/views/spread-search.ts
Labels: feature
